routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('/students');
});


//Student Module
Route::resource('students', 'StudentController');

//Student Marks Module
Route::resource('student-marks', 'StudentMarkController');

resources/views/partials/error.blade.php
@if (Session::has('error'))
<div class="alert alert-success">
    <strong>Error!</strong> {!! session('error') !!}
</div>
@endif

resources/views/partials/header.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Student Management System') }}</title>
    <link rel="stylesheet" href="{{asset('vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//cdn.jsdelivr.net/npm/@sweetalert2/theme-minimal/minimal.css" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{{asset('css/demo/style.css')}}">
    <link rel="shortcut icon" href="{{asset('images/favicon.png')}}" />
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @yield ('prepend-assets')
</head>

resources/views/partials/left-nav.blade.php
<nav class="mdc-list mdc-drawer-menu">

    <div class="mdc-list-item mdc-drawer-item">
        <a class="mdc-drawer-link" href="{{route('students.index')}}">
            <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">description</i>
            Students
        </a>
    </div>

    <div class="mdc-list-item mdc-drawer-item">
        <a class="mdc-drawer-link" href="{{route('student-marks.index')}}">
            <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">receipt</i>
            Student Mark List
        </a>
    </div>

</nav>

resources/views/partials/scripts.blade.php
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="{{asset('vendors/js/vendor.bundle.base.js')}}"></script>
<script src="{{asset('vendors/jvectormap/jquery-jvectormap.min.js')}}"></script>
<script src="{{asset('vendors/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
<script src="{{asset('js/material.js')}}"></script>
<script src="{{asset('/js/misc.js')}}"></script>
<script src="{{asset('/js/dashboard.js')}}"></script>
<script src="{{asset('/js/dataHelper.js')}}"></script>
<script src="{{asset('/js/jquery.csv.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<script src="{{asset('/js/preloader.js')}}"></script>
@yield ('append-assets')

resources/views/partials/success.blade.php
@if (Session::has('message'))
<div class="alert alert-success">
    <strong>Success!</strong> {!! session('message') !!}
</div>
@endif