routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('/students');
});


//Student Module
Route::resource('students', 'StudentController');

//Student Marks Module
Route::resource('student-marks', 'StudentMarkController');

resources/views/marks/create.blade.php
@extends('layouts.app')

@section('section-name', 'Enter Student Marks')

@section('content')
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{route('student-marks.store')}}" method="post" id="enterMarks" class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6-desktop">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                    <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);"></p>
                    {{csrf_field()}}
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                    <div class="mdc-card">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);">Enter Student Marks</p>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="student" id="student" required>
                                    <option value=" ">Select</option>
                                    @foreach(\App\Models\Students::get() as $student)
                                    <option value="{{$student->id}}" @if(old('student')==$student->id) selected @endif>{{$student->name}}</option>
                                    @endforeach
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Student</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="term" id="term" required>
                                    <option value=" ">Select</option>
                                    <option value="One" @if(old('term')=="One" ) selected @endif>One</option>
                                    <option value="Two" @if(old('term')=="Two" ) selected @endif>Two</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Term</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="maths_mark" type="text" name="maths_mark" maxlength="2" value="{{ old('maths_mark') }}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Maths Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="science_mark" type="text" name="science_mark" maxlength="2" value="{{ old('science_mark') }}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Science Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="history_mark" type="text" name="history_mark" maxlength="2" value="{{ old('history_mark') }}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter History Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <button type="submit" class="mdc-button mdc-button--raised w-100">Add Student</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('append-assets')
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>
@endsection

resources/views/marks/edit.blade.php
@extends('layouts.app')

@section('section-name', 'Edit Student Marks')

@section('content')
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{route('student-marks.update', $studentMarks->id)}}" method="post" id="editMarks" class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6-desktop">
                <input name="_method" type="hidden" value="PATCH">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                    <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);"></p>
                    {{csrf_field()}}
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                    <div class="mdc-card">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);">Edit Student Marks</p>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="student" id="student" required>
                                    <option value=" ">Select</option>
                                    @foreach(\App\Models\Students::get() as $student)
                                    <option value="{{$student->id}}" @if($studentMarks->student_id == $student->id) selected @endif>{{$student->name}}</option>
                                    @endforeach
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Student</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="term" id="term" required>
                                    <option value=" ">Select</option>
                                    <option value="One" @if($studentMarks->term == "One") selected @endif>One</option>
                                    <option value="Two" @if($studentMarks->term == "Two") selected @endif>Two</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Term</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="maths_mark" type="text" name="maths_mark" maxlength="2" value="{{$studentMarks->maths}}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Maths Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="science_mark" type="text" name="science_mark" maxlength="2" value="{{$studentMarks->science}}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Science Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="history_mark" type="text" name="history_mark" maxlength="2" value="{{$studentMarks->history}}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter History Mark</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <button type="submit" class="mdc-button mdc-button--raised w-100">Update Student Mark</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('append-assets')
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>
@endsection

resources/views/marks/index.blade.php
@extends('layouts.app')

@section('section-name', 'Student Mark List')

@section('prepend-assets')
<link rel="stylesheet" type="text/css" href="{{asset('/css/datatables.min.css')}}" />
@endsection

@section('content')
@include('partials.success')
@include('partials.error')
<div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6" style="margin-bottom: 10px;">
                <a href="{{route('student-marks.create')}}"><button class="mdc-button mdc-button--raised w-100 studentAdd">Add Student Marks</button></a>
            </div>
            <table id="studentMarks" class="table table-striped table-bordered hats-datatable" style="width:100%;margin-top:40px;">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Maths</th>
                        <th>Science</th>
                        <th>History</th>
                        <th>Term</th>
                        <th>Total Marks</th>
                        <th>Created On</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@endsection


@section('append-assets')
<script type="text/javascript" src="{{asset('/js/datatables.min.js')}}"></script>
<script>
    $(document).ready(function() {
        var table = $('#studentMarks').dataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('student-marks.index') }}",
            columns: [{
                    data: 'id',
                    name: 'id',
                    searchable: false,
                    orderable: false,
                },
                {
                    data: 'student.name',
                    name: 'student.name'
                },
                {
                    data: 'maths',
                    name: 'maths'
                },
                {
                    data: 'science',
                    name: 'science'
                },
                {
                    data: 'history',
                    name: 'history'
                },
                {
                    data: 'term',
                    name: 'term'
                },
                {
                    data: 'total_marks',
                    name: 'total_marks'
                },
                {
                    data: 'created_on',
                    name: 'created_on'
                },
                {
                    data: 'action',
                    name: 'action',
                    searchable: false,
                    orderable: false,
                },
            ],
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $("td:first", nRow).html(iDisplayIndex + 1);
                return nRow;
            },
        });
    });
</script>

@endsection