routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect('/students');
});


//Student Module
Route::resource('students', 'StudentController');

//Student Marks Module
Route::resource('student-marks', 'StudentMarkController');

app/Models/Students.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Students extends Model
{
    use HasFactory, SoftDeletes;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use DataTables;
use App\Models\Students;
use App\Services\StudentManagement;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function __construct(StudentManagement $studentManagement)
    {
        $this->studentManagement = $studentManagement;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Students::query();

            return DataTables::of($data)
                ->addColumn('action', function ($row) {
                    $btn = '<a href="' . route('students.edit', $row->id) . '" ><i style="font-size:20px;cursor: pointer;" class="fa">&#xf044;</i></a>';
                    $btn .= '<form action="' . route('students.destroy', $row->id) . '" method="post" style="display: contents;"><input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="' . csrf_token() . '"><button type="submit" style="border:none;margin-left:4px;"><i style="font-size:20px;cursor: pointer;" class="fa">&#xf014;</i></button></form>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('students.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'age' => 'required|numeric',
            'gender' => 'required',
            'teacher' => 'required',
        ]);
        $studentSave = $this->studentManagement->saveStudent($request);

        if ($studentSave)
            return redirect('/students')->with('message', 'Student Added Successfully');
        return redirect('/students')->with('error', 'Something Went Wrong');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Students::find($id);

        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'age' => 'required|numeric',
            'gender' => 'required',
            'teacher' => 'required',
        ]);
        $studentUpdate = $this->studentManagement->updateStudent($request, $id);

        if ($studentUpdate)
            return redirect('/students')->with('message', 'Student Details Updated Successfully');
        return redirect('/students')->with('error', 'Something Went Wrong');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $studentDelete = $this->studentManagement->studentDelete($id);

        if ($studentDelete)
            return redirect('/students')->with('message', 'Student Deleted Successfully');
        return redirect('/students')->with('error', 'Something Went Wrong');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('section-name', 'Add Student')

@section('content')
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{route('students.store')}}" method="post" id="addStudent" class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6-desktop">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                    <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);"></p>
                    {{csrf_field()}}
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                    <div class="mdc-card">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);">Add Student</p>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="name" type="text" name="name" value="{{ old('name') }}" required>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Student Name</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="age" type="text" name="age" value="{{ old('age') }}" maxlength="2" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Student Age</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="gender" id="gender" required>
                                    <option value=" ">Select</option>
                                    <option value="M" @if(old('gender')=="M" ) selected @endif>Male</option>
                                    <option value="F" @if(old('gender')=="F" ) selected @endif>Female</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Gender</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="teacher" id="teacher" required>
                                    <option value=" ">Select</option>
                                    <option value="Katie" @if(old('teacher')=="Katie" ) selected @endif>Katie</option>
                                    <option value="Max" @if(old('teacher')=="Max" ) selected @endif>Max</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Reporting Teacher</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <button type="submit" class="mdc-button mdc-button--raised w-100">Add Student</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('append-assets')
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('section-name', 'Add Student')

@section('content')
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{route('students.update', $student->id)}}" method="post" id="editStudent" class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6-desktop">
                <input name="_method" type="hidden" value="PATCH">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                    <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);"></p>
                    {{csrf_field()}}
                </div>
                <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                    <div class="mdc-card">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <p style="font-size: 15px; float: right; color:rgba(94, 94, 94, 0.87);">Add Student</p>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="name" type="text" name="name" value="{{$student->name}}" required>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Student Name</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined">
                                <input class="mdc-text-field__input" id="age" type="text" name="age" maxlength="2" value="{{$student->age}}" required onkeypress="return isNumberKey(event)" />
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Enter Student Age</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="gender" id="gender" required>
                                    <option value=" ">Select</option>
                                    <option value="M" @if($student->gender == "M") selected @endif>Male</option>
                                    <option value="F" @if($student->gender == "F") selected @endif>Female</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Gender</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
                            <div class="mdc-text-field mdc-text-field--outlined ">
                                <select class="mdc-text-field__input" name="teacher" id="teacher" required>
                                    <option value=" ">Select</option>
                                    <option value="Katie" @if($student->teacher_name == "Katie") selected @endif>Katie</option>
                                    <option value="Max" @if($student->teacher_name == "Max") selected @endif>Max</option>
                                </select>
                                <div class="mdc-notched-outline">
                                    <div class="mdc-notched-outline__leading"></div>
                                    <div class="mdc-notched-outline__notch">
                                        <label for="text-field-hero-input" class="mdc-floating-label">Select Reporting Teacher</label>
                                    </div>
                                    <div class="mdc-notched-outline__trailing"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                            <button type="submit" class="mdc-button mdc-button--raised w-100">Update Student</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('append-assets')
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('section-name', 'Student Management')

@section('prepend-assets')
<link rel="stylesheet" type="text/css" href="{{asset('/css/datatables.min.css')}}" />
@endsection

@section('content')
@include('partials.success')
@include('partials.error')
<div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6" style="margin-bottom: 10px;">
                <a href="{{route('students.create')}}"><button class="mdc-button mdc-button--raised w-100 studentAdd">Add Student</button></a>
            </div>
            <table id="studentTable" class="table table-striped table-bordered hats-datatable" style="width:100%;margin-top:40px;">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Reporting Teacher</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@endsection


@section('append-assets')
<script type="text/javascript" src="{{asset('/js/datatables.min.js')}}"></script>
<script>
    $(document).ready(function() {
        var table = $('#studentTable').dataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('students.index') }}",
            columns: [{
                    data: 'id',
                    name: 'id',
                    searchable: false,
                    orderable: false,
                },
                {
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'age',
                    name: 'age'
                },
                {
                    data: 'gender',
                    name: 'gender'
                },
                {
                    data: 'teacher_name',
                    name: 'teacher_name'
                },
                {
                    data: 'action',
                    name: 'action',
                    searchable: false,
                    orderable: false,
                },
            ],
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $("td:first", nRow).html(iDisplayIndex + 1);
                return nRow;
            },
        });
    });
</script>

@endsection